---
  - name: Get the Quay Instance secret
    kubernetes.core.k8s_info:
      kind: Secret
      namespace: "{{ ansible_operator_meta.namespace }}"
      name: "{{ quay_secret.name }}"
    register: quay_secret_result
    
  - name: Ensure the organization exists
    include_role:
      name: infra.quay_configuration.quay_org
    vars:
      # Connection parameters
      quay_org_host: "{{ quay_secret_result.resources[0].data.quayHost | b64decode }}"
      quay_org_token: "{{ quay_secret_result.resources[0].data.quayToken | b64decode}}"
      quay_validate_certs: "{{ quay_secret_result.data.quayValidateCerts | b64decode}}"
      # Organization name and email
      quay_org_name: "{{ ansible_operator_meta.name }}"
      quay_org_prune: "{{ quay_prune | default([]) }}" 
      quay_org_users: "{{ quay_users | default([]) }}" 
      quay_org_robots: "{{ quay_robots | default([]) }}" 
      quay_org_teams: "{{ quay_teams | default([]) }}" 
      quay_org_default_perms: "{{ quay_default_perms | default([]) }}" 
      quay_org_applications: "{{ quay_applications | default([]) }}" 
      quay_org_repositories: "{{ quay_repositories | default([]) }}" 