---
- name: Creating a organization
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Get the Quay Instance secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: "{{ ansible_operator_meta.namespace }}"
        name: "{{ quay_secret.name }}"
      register: quay_secret_result

    - name: Ensure the organization exists
      include_role:
        name: infra.quay_configuration.quay_org
      vars:
        # Connection parameters
        quay_host: "{{ quay_secret_result.resources[0].data.quayHost }}"
        quay_token: "{{ quay_secret_result.resources[0].data.quayToken }}"
        quay_validate_certs: "{{ quay_secret_result.resources[0].data.quayValidateCerts }}"
        # Organization name and email
        quay_org_name: "{{ ansible_operator_meta.name }}"
        # quay_org_email: production@example.com
        # # Proxy cache
        # quay_org_cache_registry: quay.io/sclorg
        # quay_org_cache_expiration: 3d
        # # Quota
        # quay_org_quota: 1.5 TiB
        # quay_org_warning_pct: 90
        # quay_org_reject_pct: 97
        # # Organization auto-pruning tags policies
        # quay_org_prune:
        #   - method: tags
        #     value: 15
        #     tag_pattern: nightly
        #   - method: date
        #     value: 5w
        # # User accounts to create
        # quay_org_users:
        #   - username: lvasquez
        #     email: lvasquez@example.com
        #     password: vs9mrD55NP
        #   - username: dwilde
        #     email: dwilde@example.com
        # # Robot accounts to create in the organization
        # quay_org_robots:
        #   - name: robotprod
        # # Teams to create and configure
        # quay_org_teams:
        #   - name: qa
        #     role: member
        #     members:
        #       - lvasquez
        #   - name: ops
        #     description: Operators
        #     role: creator
        #     members:
        #       - dwilde
        #       - production+robotprod
        # # Permissions to apply to new repositories in the organization
        # quay_org_default_perms:
        #   - name: ops
        #     type: team
        #     role: write
        #   - name: lvasquez
        #     type: user
        #     role: read
        # # OAuth applications
        # quay_org_applications:
        #   - name: oauth_app
        # # Repositories to create in the organization
        # quay_org_repositories:
        #   - name: small_image
        #     visibility: private
        #     perms:
        #       - name: qa
        #         type: team
        #         role: read
        #     prune:
        #       - method: tags
        #         value: 5
        #         tag_pattern: nightly
        #       - method: date
        #         value: 1w
