---
# tasks file for QuayOrganization
---
- name: Creating a production organization
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Get the Quay Instance secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: "{{ quay_secret.namespace }}"
        name: "{{ quay_secret.name }}"
      register: quay_secret_result

    - name: Ensure the organization is deleted
      quay_organization:
        quay_host: "{{ quay_secret_result.resources[0].data.quayHost }}"
        quay_username: "{{ quay_secret_result.resources[0].data.quayUsername }}"
        quay_password: "{{ quay_secret_result.resources[0].data.quayPassword }}"
        quay_validate_certs: "{{ quay_secret_result.resources[0].data.quayValidateCerts }}"
        name: "{{ ansible_operator_meta.name }}"
        state: absent