---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quayorganizations.quay.conclusionxforce.cloud
spec:
  group: quay.conclusionxforce.cloud
  names:
    kind: QuayOrganization
    listKind: QuayOrganizationList
    plural: quayorganizations
    singular: quayorganization
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: QuayOrganization is the Schema for the quayorganizations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of QuayOrganization
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              quaySecret:
                description: QuaySecret defines a secret containing the information regarding your quay instance
                type: object
                properties:
                  name:
                    description: Name of the Kubernetes Secret containing quay information containing (quayHost, quayUser, quayPassword, quayValidateCerts)
                    type: string
          status:
            description: Status defines the observed state of QuayOrganization
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
